## Introduction


In [43]:
import numpy as np

In [9]:
# Create an array with 3 integers, starting from the default integer 0.
b = np.arange(3)
print(b)

[0 1 2]


In [8]:
# Create an array that starts from the integer 1, ends at 20, incremented by 3.
c = np.arange(1, 20, 3)
print(c)

[ 1  4  7 10 13 16 19]


In [20]:
lin_spaced_arr = np.linspace(0, 100, 16)
print(lin_spaced_arr)

matrix = np.reshape(lin_spaced_arr, (4, 4))
print(matrix)

[  0.           6.66666667  13.33333333  20.          26.66666667
  33.33333333  40.          46.66666667  53.33333333  60.
  66.66666667  73.33333333  80.          86.66666667  93.33333333
 100.        ]
[[  0.           6.66666667  13.33333333  20.        ]
 [ 26.66666667  33.33333333  40.          46.66666667]
 [ 53.33333333  60.          66.66666667  73.33333333]
 [ 80.          86.66666667  93.33333333 100.        ]]


In [ ]:
ones_arr = np.ones(16)
print(ones_arr)

matrix = np.reshape(ones_arr, (4, 4))
print(matrix)

In [ ]:
ones_arr = np.ones(16)
print(ones_arr)

matrix = np.reshape(ones_arr, (4, 4))
print(matrix)

In [12]:
# Dimension of the 2-D array multi_dim_arr
matrix.ndim

2

In [13]:
# Shape of the 2-D array multi_dim_arr
# Returns shape of 2 rows and 3 columns
matrix.shape

(4, 4)

In [14]:
# Size of the array multi_dim_arr
# Returns total number of elements
matrix.size

16

In [16]:
arr_1 = np.array([2, 4, 6])
arr_2 = np.array([1, 3, 5])

addition = arr_1 + arr_2
print(addition)

multiplication = arr_1 * arr_2
print(multiplication)

scalar_multiplication = arr_1 * 2
print(scalar_multiplication)

[ 3  7 11]
[ 2 12 30]
[ 4  8 12]


In [19]:
two_dim = np.array(([1, 2, 3], [4, 5, 6], [7, 8, 9]))

print(two_dim[2, 1])
print(two_dim[1, 2])

8
6


In [30]:
a = np.linspace(0, 200, 25)
print(a)

[  0.           8.33333333  16.66666667  25.          33.33333333
  41.66666667  50.          58.33333333  66.66666667  75.
  83.33333333  91.66666667 100.         108.33333333 116.66666667
 125.         133.33333333 141.66666667 150.         158.33333333
 166.66666667 175.         183.33333333 191.66666667 200.        ]


In [26]:
sliced_arr = a[2:]
print(sliced_arr)

[ 16.66666667  25.          33.33333333  41.66666667  50.
  58.33333333  66.66666667  75.          83.33333333  91.66666667
 100.         108.33333333 116.66666667 125.         133.33333333
 141.66666667 150.         158.33333333 166.66666667 175.
 183.33333333 191.66666667 200.        ]


In [27]:
sliced_arr = a[:3]
print(sliced_arr)

[ 0.          8.33333333 16.66666667]


In [28]:
sliced_arr = a[::2]
print(sliced_arr)

[  0.          16.66666667  33.33333333  50.          66.66666667
  83.33333333 100.         116.66666667 133.33333333 150.
 166.66666667 183.33333333 200.        ]


In [ ]:
# Note that a == a[:] == a[::]
print(a == a[:] == a[::])

In [32]:
two_dim = np.reshape(a, (5, 5))
print(two_dim)

[[  0.           8.33333333  16.66666667  25.          33.33333333]
 [ 41.66666667  50.          58.33333333  66.66666667  75.        ]
 [ 83.33333333  91.66666667 100.         108.33333333 116.66666667]
 [125.         133.33333333 141.66666667 150.         158.33333333]
 [166.66666667 175.         183.33333333 191.66666667 200.        ]]


In [33]:
# Slice the two_dim array to get the first two rows
print(two_dim[0:2])

[[ 0.          8.33333333 16.66666667 25.         33.33333333]
 [41.66666667 50.         58.33333333 66.66666667 75.        ]]


In [36]:
# Similarily, slice the two_dim array to get the last two rows
sliced_two_dim_rows = two_dim[1:4]
print(sliced_two_dim_rows)

[[ 41.66666667  50.          58.33333333  66.66666667  75.        ]
 [ 83.33333333  91.66666667 100.         108.33333333 116.66666667]
 [125.         133.33333333 141.66666667 150.         158.33333333]]


In [37]:
# Get the second column
sliced_two_dim_cols = two_dim[:, 1]
print(sliced_two_dim_cols)

[  8.33333333  50.          91.66666667 133.33333333 175.        ]


In [38]:
a1 = np.array([[1, 1], [2, 2]])
a2 = np.array([[3, 3], [4, 4]])
print(f"a1:\n{a1}")
print(f"a2:\n{a2}")

a1:
[[1 1]
 [2 2]]
a2:
[[3 3]
 [4 4]]


In [39]:
# Stack the arrays vertically
vert_stack = np.vstack((a1, a2))
print(vert_stack)

[[1 1]
 [2 2]
 [3 3]
 [4 4]]


In [40]:
# Stack the arrays horizontally
horz_stack = np.hstack((a1, a2))
print(horz_stack)

[[1 1 3 3]
 [2 2 4 4]]


In [41]:
# Split the horizontally stacked array into 2 separate arrays of equal size
horz_split_two = np.hsplit(horz_stack, 2)
print(horz_split_two)

# Split the horizontally stacked array into 4 separate arrays of equal size
horz_split_four = np.hsplit(horz_stack, 4)
print(horz_split_four)

# Split the horizontally stacked array after the first column
horz_split_first = np.hsplit(horz_stack, [1])
print(horz_split_first)

[array([[1, 1],
       [2, 2]]), array([[3, 3],
       [4, 4]])]
[array([[1],
       [2]]), array([[1],
       [2]]), array([[3],
       [4]]), array([[3],
       [4]])]
[array([[1],
       [2]]), array([[1, 3, 3],
       [2, 4, 4]])]


In [42]:
# Split the vertically stacked array into 2 separate arrays of equal size
vert_split_two = np.vsplit(vert_stack, 2)
print(vert_split_two)

# Split the horizontally stacked array into 4 separate arrays of equal size
vert_split_four = np.vsplit(vert_stack, 4)
print(vert_split_four)

# Split the horizontally stacked array after the first and third row
vert_split_first_third = np.vsplit(vert_stack, [1, 3])
print(vert_split_first_third)

[array([[1, 1],
       [2, 2]]), array([[3, 3],
       [4, 4]])]
[array([[1, 1]]), array([[2, 2]]), array([[3, 3]]), array([[4, 4]])]
[array([[1, 1]]), array([[2, 2],
       [3, 3]]), array([[4, 4]])]


## Matrix Equations


In [3]:
import numpy as np
import matplotlib.pyplot as plt

In [28]:
A = np.array([[-1, 3], [3, 2]], dtype=np.dtype(float))
b = np.array([7, 1], dtype=np.dtype(float))

print("Matrix A:")
print(A)
print("\nArray b:")
print(b)

Matrix A:
[[-1.  3.]
 [ 3.  2.]]

Array b:
[7. 1.]


In [8]:
print(f"Shape of A: {np.shape(A)}")
print(f"Shape of A: {np.shape(b)}")

Shape of A: (2, 2)
Shape of A: (2,)


In [25]:
# To find the solution of the linear system
try:
    x = np.linalg.solve(A, b)
    print(f"Solution: {x}")
except np.linalg.LinAlgError as err:
    print(err)

Solution: [-1.  2.]


In [11]:
# Determinant
d = np.linalg.det(A)

print(f"{d:.2f}")

-11.00


In [16]:
A_system = np.hstack((A, b.reshape((2, 1))))

print(A_system)

[[-1.  3.  7.]
 [ 3.  2.  1.]]


In [64]:
A = np.array([[1, 2, 3], [2, 6, 12], [4, -8, 4]], dtype=np.dtype(float))
b = np.array([10, 4, 8], dtype=np.dtype(float))

try:
    x = np.linalg.solve(A, b)
    print(f"Solution: {x}")
except np.linalg.LinAlgError as err:
    print(f"Error: {err}")

Solution: [14.  4. -4.]


In [62]:
A = np.array([[1, 2, 3], [2, 6, 12], [4, -8, 4]], dtype=np.dtype(float))
d = np.linalg.det(A)

print(f"Determinant: {d:.2f}")

# Multiply a row
A = np.array([[2, 4, 6], [2, 6, 12], [4, -8, 4]], dtype=np.dtype(float))
d = np.linalg.det(A)

print(f"Determinant: {d:.2f}")

# Swapping rows
A = np.array([[2, 6, 12], [1, 2, 3], [4, -8, 4]], dtype=np.dtype(float))
d = np.linalg.det(A)

print(f"Determinant: {d:.2f}")

Determinant: 80.00
Determinant: 160.00
Determinant: -80.00


## Gauss elimination


In [65]:
from scipy.linalg import lu

A = np.array([[2, 1, 5], [1, 3, 1], [3, 4, 6]], dtype=np.dtype(float))

pl, u = lu(A, permute_l=True)

gauss = u

print(f"Identity matrix: {gauss}")

Identity matrix: [[ 3.          4.          6.        ]
 [ 0.          1.66666667 -1.        ]
 [ 0.          0.          0.        ]]
